### ISSUE TITLE
Might want to pull your api creds from your GPT script

### ISSUE THREAD

**Issue by Jason-K** [Kuanchiliao1/PersonalAHK#2]
Cool script! Thanks for the code, sans api key of course.

**Comment by Kuanchiliao1** [comment]
Hey, thanks for letting me know! I actually moved all of that code for that functionality into this repo: https://github.com/Kuanchiliao1/AHK_AI

The key has been deactivated for a while now and I forgot to remove the files completely, will do that now :)
